// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoeF79Bo4RreXzwgmYbEGLKPKZzYbgrnc',
    appId: '1:906266666655:web:b9d505d89556244cb264aa',
    messagingSenderId: '906266666655',
    projectId: 'sortir-development',
    authDomain: 'sortir-development.firebaseapp.com',
    storageBucket: 'sortir-development.appspot.com',
    measurementId: 'G-4QZWCJZD4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXhUQupjzvF0DXC5UqtY5uc9ZRLrYdcng',
    appId: '1:906266666655:android:b3f9ded1adc9f987b264aa',
    messagingSenderId: '906266666655',
    projectId: 'sortir-development',
    storageBucket: 'sortir-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8AbL0FnUs92YDrh-JE1iGkFKV4GD6bK0',
    appId: '1:906266666655:ios:bf574e20fa8e60d0b264aa',
    messagingSenderId: '906266666655',
    projectId: 'sortir-development',
    storageBucket: 'sortir-development.appspot.com',
    androidClientId: '906266666655-7e3uq0hapf30assds4hk6mu27k3os35s.apps.googleusercontent.com',
    iosClientId: '906266666655-hn3o6v3kukil9bkbkcb2brjd77n5cddg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sortirDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8AbL0FnUs92YDrh-JE1iGkFKV4GD6bK0',
    appId: '1:906266666655:ios:bf574e20fa8e60d0b264aa',
    messagingSenderId: '906266666655',
    projectId: 'sortir-development',
    storageBucket: 'sortir-development.appspot.com',
    androidClientId: '906266666655-7e3uq0hapf30assds4hk6mu27k3os35s.apps.googleusercontent.com',
    iosClientId: '906266666655-hn3o6v3kukil9bkbkcb2brjd77n5cddg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sortirDev',
  );
}
